const MINOR_OFFENSES = [
  "Dress Code Violation",
  "Improper Uniform",
  "Improper Haircut",
  "Unauthorized Hair Color",
  "Wearing Earrings",
  "Use of Cosmetics/Nail Polish",
  "Unnecessary Talking",
  "Shouting",
  "Howling",
  "Eating Inside Classroom",
  "Extreme Quarrels",
  "Minor Classroom Disruption",
  "Use of Impolite Words",
  "Cursing",
  "Teasing",
  "Name Calling",
  "Habitual Absences",
  "Unnecessary Use of Chat Box",
  "Unresponsive During Online Classes",
  "Leaving Online Conference Without Permission",
  "Turning Off Camera Without Valid Reason",
  "Improper Camera Visibility",
  "Habitual Tardiness",
  "Inappropriate Profile Picture/Background",
  "Unsigned School Correspondence",
  "Late Submission of Reply Slips",
  "Non-submission of Reply Slips",
  "Failure to Submit Excuse Letter",
  "Loss of Violation Report",
  "Littering",
  "Violation of Library Rules",
  "Failure to Return Borrowed Materials",
  "Not Wearing School ID",
  "Playing Cards",
  "Rough Play",
  "Horseplaying",
  "Refusal to Replace Damaged Property",
  "Using Cellphone During Examination",
  "Failure to Present School ID",
  "Tampering School ID",
  "Tampering Library Card",
  "Loitering",
  "Lending School ID",
  "Using Someone Else's ID",
  "Locker Policy Violation",
  "Eating in Restricted Areas",
  "Unauthorized Gadgets",
  "Unauthorized Cellphone Use",
];

const MAJOR_OFFENSES = [
  "Sharing Account Credentials",
  "Piracy",
  "Unauthorized Downloading",
  "Posting Screenshots Without Consent",
  "Defamation",
  "Slander",
  "Recording Without Consent",
  "Cyberbullying",
  "Cyber Baiting",
  "Unauthorized Transactions",
  "Viewing Pornographic Materials",
  "Selling Without Approval",
  "Spreading Fake News",
  "Harassment",
  "Threatening Messages",
  "Profanity",
  "Using Portal for Political Activities",
  "Using Portal for Gambling",
  "Anonymous Harassing Emails",
  "Threatening Other Students",
  "Desecration of Religious Items",
  "Disrespect During Ceremonies",
  "Improper Use of Internet",
  "Withholding Information",
  "Petty Theft",
  "Stealing",
  "Possession of Pornographic Materials",
  "Threatening School Personnel",
  "Unauthorized Solicitation",
  "Disrespect to School Authorities",
  "Disobedience",
  "Defiance",
  "Assault",
  "Abusive Behavior",
  "Bringing School Into Disrepute",
  "Forgery",
  "Cheating",
  "Plagiarism",
  "Academic Dishonesty",
  "Vandalism",
  "Defacing School Property",
  "Destroying School Property",
  "Tampering School Records",
  "Possession of Immoral Materials",
  "Gambling",
  "Mischief",
  "Unauthorized Use of School Equipment",
  "Spreading False Information",
  "Instigating a Fight",
  "Unauthorized Leaving of Campus",
  "Possession of Liquor",
  "Possession of Cigarettes",
  "Possession of Vape",
  "Possession of Deadly Weapon",
  "Fighting",
  "Physical Injury",
  "Physical Assault",
  "Entering Bars While in Uniform",
  "Tampering Fire Safety Equipment",
  "Habitual Violation of School Rules",
  "Smoking Inside Campus",
  "Smoking During School Activities",
  "Drug Possession",
  "Drug Selling",
  "Public Display of Affection",
  "Indecent Conduct",
  "Immoral Conduct",
  "Pregnancy-related Misconduct",
  "Sex Video/Scandal Involvement",
  "Joining Unauthorized Fraternities",
  "Hazing",
  "Voyeurism",
];

export const getOffenseSeverity = (offense) => {
  if (MAJOR_OFFENSES.includes(offense)) {
    return "High";
  }

  if (MINOR_OFFENSES.includes(offense)) {
    return "Low";
  }

  // Custom "Other"
  return "Medium";
};