import jsPDF from "jspdf";

/**
 * Professional Intervention Report Generator
 */
export const exportInterventionPDF = (selected, interventions = {}) => {
  if (!selected) return;

  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = 210;
  let y = 20;

  const addText = (text, size = 12, color = [0, 0, 0]) => {
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
    pdf.text(text, 15, y);
    y += size * 0.6 + 4;
  };

  const addLine = () => {
    pdf.setDrawColor(200);
    pdf.line(15, y, 195, y);
    y += 6;
  };

  const addSection = (title) => {
    y += 4;
    pdf.setFontSize(14);
    pdf.setTextColor(0, 150, 80);
    pdf.text(title, 15, y);
    y += 6;
    addLine();
  };

  const studentInterventions = interventions[selected._id] || [];

  // ================= HEADER =================
  pdf.setFontSize(18);
  pdf.setTextColor(0, 150, 80);
  pdf.text("EDUGUARD DISCIPLINE REPORT", 15, y);
  y += 10;

  pdf.setFontSize(10);
  pdf.setTextColor(100);
  pdf.text("Our Lady of the Holy Rosary - General Trias, Cavite", 15, y);
  y += 10;

  addLine();

  // ================= STUDENT INFO =================
  addSection("Student Information");

  addText(`Name: ${selected.studentName}`);
  addText(`Offense: ${selected.offense}`);

  // ================= SUMMARY =================
  addSection("Case Summary");

  addText(`Total Interventions: ${studentInterventions.length}`);

  const status =
    studentInterventions.length === 0
      ? "No Action Taken"
      : studentInterventions.some(i => i.status === "active")
      ? "Active Case"
      : "Resolved / Monitoring";

  addText(`Status: ${status}`);

  // ================= TIMELINE =================
  addSection("Intervention Timeline");

  if (studentInterventions.length === 0) {
    addText("No interventions recorded yet.", 11, [120, 120, 120]);
  } else {
    studentInterventions.forEach((i, index) => {
      addText(`${index + 1}. ${i.type.toUpperCase()}`, 12);
      addText(`   ${i.description || "No description"}`, 10, [80, 80, 80]);
      addText(`   Status: ${i.status}`, 10, [100, 100, 100]);
      y += 2;
    });
  }

  // ================= FOOTER =================
  y = 270;
  pdf.setFontSize(9);
  pdf.setTextColor(150);
  pdf.text(
    `Generated by EduGuard System • ${new Date().toLocaleDateString()}`,
    15,
    y
  );

  pdf.save(`${selected.studentName}_discipline_report.pdf`);
};